### ISSUE TITLE
Require statement

### ISSUE THREAD

**Issue by con-ssc** [derekfinlinson/xrm-webapi#10]
So since I haven't found a helper function for require is not a native function, at least not in browsers. It may work in nodejs though.
So this will not work unless you specify another dependency to a module loader.
```JavaScript
var es6_promise_1 = require("es6-promise");
```

**Comment by derekfinlinson** [comment]
I've actually never tried just using the module as is. I use webpack to bundle it up with any necessary code. Have you tried just loading it in the form? TypeScript should transpile it down to ES5 so I assume it would work.

**Comment by con-ssc** [comment]
No I haven't tried it, was just having a look at the repo.
So how would you use the xrm-webapi lets say if you had to add some javascript to an account form? I would be interested in the workflow with javascript files on your side.

**Comment by derekfinlinson** [comment]
These are both very much a WIP but if you take a look at [xrm-templates](https://github.com/derekfinlinson/xrm-templates/tree/master/WebResources) and [generator-xrm-webreource](https://github.com/derekfinlinson/generator-xrm-webresource)  you can sort of see the flow. Need to get some documentation up.

Basically I write everything in TypeScript so I can use the [xrm typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/555ea54770b8576162e761e344de969d6e960869/xrm). Then I use webpack to bundle each script (such as AccountForm.ts) along with it's dependencies into a single file. Then I use David Yacks [gulp-webresource](https://github.com/davidyack/gulp-webresource) to automatically upload to CRM.

**Comment by con-ssc** [comment]
Haven't heard about the gulp-webresource thing yet, I will have a look.
So how did you persuade your superiors that you are allowed to use TypeScript in the first place :D

**Comment by derekfinlinson** [comment]
Fortunately, we're a pretty small shop with only a handful of developers so don't have much in the way of an org hierarchy. Even if you don't use most of it's cooler features, it's worth it for the Xrm typings alone. It's saved me many a trip to the Xrm.Page documentation.

**Comment by con-ssc** [comment]
Does the adal auth also works against on premise?

**Comment by derekfinlinson** [comment]
I wouldn't think so since I believe it's specific to Office 365 OAuth authentication
