### ISSUE TITLE
Retrieve Metadata

### ISSUE THREAD

**Issue by iamgmd** [derekfinlinson/xrm-webapi#11]
Is it possible to retrieve Metadata using the webapi, like EntityDefinitions, etc?

**Comment by derekfinlinson** [comment]
You can. It follows the same patters as retrieving data so you should be able to use the existing retrieveMultiple method. There are a couple differences that could be implemented so I'll take a look at doing that.

https://msdn.microsoft.com/en-us/library/mt607833.aspx

**Comment by iamgmd** [comment]
That's great, appreciate it and it does work. Will be great to see what else you will implement. For my scenario, I need to get all entities, all attributes, etc and build a local schema from it to which the client application can use to build UI's from. i.e. select entity -> select field -> has 100 chars, is text, etc.
