### ISSUE TITLE
Paging not Implemented for retrieveMultiple

### ISSUE THREAD

**Issue by thutch10** [derekfinlinson/xrm-webapi#17]
In the xrm-webapi/src/xrm-webapi.ts file, there is a function called getNextPage() which says it implements paging for retrieveMultiple.  However, when I look at retrieveMultiple, there is no reference to getNextPage() and paging doesn't seem to be implemented in a different way.

**Comment by derekfinlinson** [comment]
I didn't want to force the user to retrieve all pages in case they only want the first page. You can call that method after each successful retrieveMultiple if you want to get the next page:

```
const api = new WebApi("8.2");

const accounts = await api.retrieveMultiple("accounts", "$select=accountid");

// Get odata.nextlink from retrieveMultiple
const next = accounts["@odata.nextlink"];

const nextAccounts = await api.getNextPage(next);
```

**Comment by thutch10** [comment]
I understand.  It might be good to include that in your documentation.  I'm guessing some other people will assume as I did that retrieveMultiple will return everything regardless of size.
