### ISSUE TITLE
Consider adding CRM specific types as TS definitions

### ISSUE THREAD

**Issue by shytikov** [derekfinlinson/xrm-webapi#2]
It would be nice to have CRM specific types be defined more strictly.

For example, `OptionSetValue`, `Money` or `EntityReference`, etc.

**Comment by shytikov** [comment]
It would also be nice to have more strict rules on `Guid` type, which is not CRM specific, but there are some bugs in turbo forms that causes validations fire twice if `Guid` to lookup filed was not supplied in uppercase! So it would be nice to ensure that `Guid`s are always in uppercase, have right length, no braces, etc.

**Comment by derekfinlinson** [comment]
I added Guid, Entity and generic Attribute type for now. I'll have to think about how to add the other types, especially EntityReference, since the Web API expects certain formats for those in Create/Update.

**Comment by shytikov** [comment]
Regarding `Attribute`, you can actually reuse [this definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/xrm/xrm.d.ts#L989). And that file actually contains more specific attribute types, as well as attribute values.

**Comment by shytikov** [comment]
Maybe is not good idea... it's better to have less dependencies as possible...

**Comment by derekfinlinson** [comment]
That library has a different definition of Attribute since it's form the Xrm.Page attributes. My library is really only for calling the Web API. It's a good idea to use that in your form scripts though for helping build your Web API requests,
