### ISSUE TITLE
Xrm is not defined in model.js

### ISSUE THREAD

**Issue by johnpatoki** [derekfinlinson/xrm-webapi#29]
when try to run angular app i got error in model.js of "Xrm not defined"

![image](https://user-images.githubusercontent.com/24723317/53824642-44988000-3f96-11e9-86a8-841e5b4aed01.png)

**Comment by derekfinlinson** [comment]
You probably need to include the [ClientGlobalContext.js.aspx](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx) script in your HTML file.

**Comment by derekfinlinson** [comment]
@johnpatoki Did you get this resolved?
