### ISSUE TITLE
Angular app and IE

### ISSUE THREAD

**Issue by AnatoliyVesh** [derekfinlinson/xrm-webapi#30]
Hi! 
I created an Angular SPA for D365. All works fine in Edge/Chrome but doesn't in IE.
I got SCRIP1002: Syntax error (some problem with class WebApiConfig).
Maybe you have some idea about how to fix it?

**Comment by luisaceituno** [comment]
There is currently no way to fix this easily in Angular. I don't understand why this library doesn't create es5 compliant JavaScript, since the main target use is in enterprise applications where IE11 is still very much a norm...

**Comment by derekfinlinson** [comment]
I switched the module to compile to es5 instead of es2017. This should fix your issue

**Comment by luisaceituno** [comment]
Thank you @derekfinlinson!
