### ISSUE TITLE
Unable to execute batch update records with batchOperation

### ISSUE THREAD

**Issue by lvhv91** [derekfinlinson/xrm-webapi#35]
Based on the source code it seems that the batchOperation function can only create multiple records in bulk. For updating records it requires the HTTP PATCH method, currently it's set to POST: (https://github.com/derekfinlinson/xrm-webapi/blob/66fb684ba92a9a6a093145f6ab5e476c211b3198/src/webapi.ts#L705

Is there a way to override this value or could it be that I have overlooked a configuration?

**Comment by derekfinlinson** [comment]
This is fixed in #36. You can specify which HTTP method to use for each change set
