### ISSUE TITLE
I have doubts about `getRequest` method

### ISSUE THREAD

**Issue by shytikov** [derekfinlinson/xrm-webapi#9]
This line in particular:

```
const context = typeof GetGlobalContext != "undefined" ? GetGlobalContext() : Xrm.Page.context;
```

When I call this function from within CRM (using FF) I get error: `ReferenceError: GetGlobalContext is not defined`.

Most likely in this case it's better to use `Xrm.Page.context` instead. 

I have fix, but from #8 experience some unwanted commits can sneak through, so I would give here function that I proposing to introduce to be more flexible in determining context:

```
private static getGlobalContext() {
    // If script was called from CRM form Xrm.Page.context object is available
    if (Xrm && Xrm.Page && Xrm.Page.context) {
        return Xrm.Page.context;
    }

    // If script was called from custom web resource most likely GetGlobalContext() function is available.
    // It would be able to provide script with needed context object.  
    if (typeof GetGlobalContext != "undefined") {
        return GetGlobalContext();
    }

    throw Error("MS Dynamics CRM Page context was not found");
}
```

**Comment by shytikov** [comment]
Sorry I'm idiot. I misunderstood TS syntax.

**Comment by derekfinlinson** [comment]
No worries. Might not be a bad idea to make sure one of the two is valid though and through an error if not. Right now it's assuming you're either on a form or correctly added the client script to your web resource.

Thanks for contributing and testing.

**Comment by shytikov** [comment]
it was stupid error :) I messed up `:` as type definition with `:` as part of `?:` statement...

Shame!
Shame!
Shame!
